language: bash

sudo: required

script:
- curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
- echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
- sudo apt update
- sudo apt install gh
- gh extension install github/gh-codeql
- gh codeql set-channel nightly
- gh codeql version
- git clone https://github.com/apache/commons-io
- gh codeql database create -l java -s commons-io commons-io-db
- gh codeql database analyze commons-io-db

