name: "CodeQL"

on:
  push:
    branches: [main, ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 11 * * 1'

jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run:
        apt update
        apt install strace
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      # Override language selection by uncommenting this and choosing your languages
      with:
        languages: cpp
    - run: printenv
      shell: strace bash -e {0}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
