name: "Test"

on:
 workflow_dispatch:
 
jobs:
  analyze:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-strict: false
        ssh-key: ${{ secrets.SSH_KEY }}
    
    - name: Clone
      run: |
        echo '${{ secrets.SSH_KEY }}' > "${{ runner.temp }}/ssh_key"
        cmd /c icacls "${{ runner.temp }}/ssh_key" /inheritance:r
        git clone git@github.com:github/lgtm-mirror-amazon-cognito-js.git
      env:
        GIT_SSH_COMMAND: '"C:\Windows\System32\OpenSSH\ssh.exe" -o StrictHostKeyChecking=no -i "${{ runner.temp }}/ssh_key" -o "UserKnownHostsFile=${{ runner.temp }}/known_hosts"'
