name: "Test"

on:
 workflow_dispatch:
 
jobs:
  analyze:
    runs-on: windows-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-strict: false
        ssh-key: ${{ secrets.SSH_KEY }}
        repository: github/semmle-resources
    - name: Update Path
      run: echo "##[add-path]${{ github.workspace }}/msys/bin"
    - name: Setup key
      run: |
        echo ${Path}
        where make
        make --help
        dir ${{ github.workspace }}/msys/bin 
        echo '${{ secrets.SSH_KEY }}' > "${{ runner.temp }}/ssh_key"
        cmd /c icacls "${{ runner.temp }}/ssh_key" /inheritance:r
    - name: Clone with OpenSSH
      env:
        GIT_SSH_COMMAND: '"C:\Windows\System32\OpenSSH\ssh.exe" -v -o StrictHostKeyChecking=no -i "${{ runner.temp }}/ssh_key" -o "UserKnownHostsFile=${{ runner.temp }}/known_hosts"'
      run:
        git clone git@github.com:github/lgtm-mirror-amazon-cognito-js.git one
      shell: bash

    - name: Clone with SSH from PATH
      env:
        GIT_SSH_COMMAND: 'ssh -v -o StrictHostKeyChecking=no -i "${{ runner.temp }}/ssh_key" -o "UserKnownHostsFile=${{ runner.temp }}/known_hosts"'
      run:
        git clone git@github.com:github/lgtm-mirror-amazon-cognito-js.git two
      shell: bash

    - name: Clone with make
      env:
        GIT_SSH_COMMAND: 'ssh -v -o StrictHostKeyChecking=no -i "${{ runner.temp }}/ssh_key" -o "UserKnownHostsFile=${{ runner.temp }}/known_hosts"'
      run: |
        echo $'all:\n\tgit clone git@github.com:github/lgtm-mirror-amazon-cognito-js.git three' > Makefile 
        make
      shell: bash



 
