name: "Test"

on:
 workflow_dispatch:
 
jobs:
  analyze:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-strict: false
        ssh-key: ${{ secrets.SSH_KEY }}
    
    - name: Clone
      run: git clone git@github.com:github/lgtm-mirror-amazon-cognito-js.git
